import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Blog from './blog';

export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Everyday Blogger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Sumit&apos;s Blog.</a>
        </h1>

        <p className={styles.description}>
          Get the Right things you are searching for!!
        </p>

        <div className={styles.grid}>

          <h2>Recent Blogs</h2>
          <Blog/>
          </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
